spring:
  datasource:
    url: "jdbc:mysql://localhost/my_library"
    username: "root"
    password: "1597531352"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hiberneate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect